apiVersion: v1
kind: Service
metadata:
  name: ares-backend-service
  namespace: devops-assignment
spec:
  selector:
    app: ares-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
